apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'Loki'

  - name: Redis-1
    type: redis-datasource
    access: proxy
    url: redis://redis-1:6379
    editable: true
    jsonData:
      client: standalone
      poolSize: 5

  - name: Redis-2
    type: redis-datasource
    access: proxy
    url: redis://redis-2:6379
    editable: true
    jsonData:
      client: standalone
      poolSize: 5

  - name: Redis-3
    type: redis-datasource
    access: proxy
    url: redis://redis-3:6379
    editable: true
    jsonData:
      client: standalone
      poolSize: 5

