version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
      - Nats__Url=nats://nats:4222
      - DistributedId__WorkerId=1
      - DistributedId__DataCenterId=1
    depends_on:
      - redis
      - nats
    networks:
      - catga-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - catga-network
    volumes:
      - redis-data:/data

  nats:
    image: nats:2-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222"]
    networks:
      - catga-network
    volumes:
      - nats-data:/data

networks:
  catga-network:
    driver: bridge

volumes:
  redis-data:
  nats-data:

