---
# Redis 主从集群配置
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: catga-cluster
  labels:
    app: redis
spec:
  selector:
    app: redis
  clusterIP: None
  ports:
    - name: redis
      port: 6379

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: catga-cluster
data:
  redis.conf: |
    appendonly yes
    appendfsync everysec
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: catga-cluster
  labels:
    app: redis
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: init-redis
          image: redis:7-alpine
          command:
            - bash
            - "-c"
            - |
              set -ex
              # 从 pod 名称生成 server-id
              [[ $(hostname) =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              # 如果不是第一个实例，配置为从节点
              if [[ $ordinal -ne 0 ]]; then
                echo "replicaof redis-0.redis.catga-cluster.svc.cluster.local 6379" >> /etc/redis/redis.conf
              fi
          volumeMounts:
            - name: config
              mountPath: /etc/redis
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
              name: redis
          command:
            - redis-server
            - /etc/redis/redis.conf
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/redis
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: redis-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

---
# Redis 主节点服务（读写）
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: catga-cluster
  labels:
    app: redis
spec:
  selector:
    app: redis
    statefulset.kubernetes.io/pod-name: redis-0
  ports:
    - name: redis
      port: 6379
      targetPort: 6379

---
# Redis 对外服务（LoadBalancer）
apiVersion: v1
kind: Service
metadata:
  name: redis-client
  namespace: catga-cluster
  labels:
    app: redis
spec:
  selector:
    app: redis
  type: LoadBalancer
  ports:
    - name: redis
      port: 6379
      targetPort: 6379

