using Catga.Core;
using MemoryPack;
using OrderSystem.Api.Domain;
using Catga.Abstractions;

namespace OrderSystem.Api.Messages;

/// <summary>
/// Create order command (with auto-generated debug capture via Source Generator)
/// Demonstrates: CQRS pattern, automatic error handling, rollback mechanism
/// </summary>
[MemoryPackable]
public partial record CreateOrderCommand(
    string CustomerId,
    List<OrderItem> Items,
    string ShippingAddress,
    string PaymentMethod
) : IRequest<OrderCreatedResult>;  // MessageId will be auto-generated by Source Generator

/// <summary>
/// Create order command using Flow orchestration for automatic compensation.
/// Demonstrates: Zero-cost saga pattern with automatic rollback on failure.
///
/// Flow steps with automatic compensation:
/// 1. Check Inventory (read-only, no compensation)
/// 2. Create Order → Compensation: Mark order as failed
/// 3. Reserve Inventory → Compensation: Release inventory
/// 4. Process Payment → Compensation: Refund payment
/// 5. Confirm Order (final step, no compensation)
///
/// On any failure, compensations execute in reverse order automatically.
/// </summary>
[MemoryPackable]
public partial record CreateOrderFlowCommand(
    string CustomerId,
    List<OrderItem> Items,
    string ShippingAddress,
    string PaymentMethod
) : IRequest<OrderCreatedResult>;

[MemoryPackable]
public partial record OrderCreatedResult(
    string OrderId,
    decimal TotalAmount,
    DateTime CreatedAt
);

/// <summary>
/// Cancel order command
/// Demonstrates: Simple command handling, state transitions
/// </summary>
[MemoryPackable]
public partial record CancelOrderCommand(
    string OrderId,
    string Reason
) : IRequest;  // MessageId will be auto-generated by Source Generator

/// <summary>
/// Get order query
/// Demonstrates: Query pattern, read model
/// </summary>
[MemoryPackable]
public partial record GetOrderQuery(
    string OrderId
) : IRequest<Order?>;  // MessageId will be auto-generated by Source Generator

// ===== Flow 服务编排示例 =====

/// <summary>
/// Reserve inventory command
/// </summary>
[MemoryPackable]
public partial record ReserveInventoryCommand(
    string OrderId,
    List<OrderItem> Items
) : IRequest<ReserveInventoryResult>;

[MemoryPackable]
public partial record ReserveInventoryResult(string ReservationId);

/// <summary>
/// Release inventory command (compensation for ReserveInventory)
/// </summary>
[MemoryPackable]
public partial record ReleaseInventoryCommand(string ReservationId) : IRequest;

/// <summary>
/// Process payment command
/// </summary>
[MemoryPackable]
public partial record ProcessPaymentCommand(
    string OrderId,
    decimal Amount,
    string PaymentMethod
) : IRequest<ProcessPaymentResult>;

[MemoryPackable]
public partial record ProcessPaymentResult(string PaymentId);

/// <summary>
/// Refund payment command (compensation for ProcessPayment)
/// </summary>
[MemoryPackable]
public partial record RefundPaymentCommand(string PaymentId) : IRequest;

// ===== Flow 使用示例 =====
//
// var result = await Flow.Create("CreateOrder")
//     .Step("ReserveInventory",
//         () => mediator.SendAsync<ReserveInventoryCommand, ReserveInventoryResult>(cmd),
//         result => mediator.SendAsync(new ReleaseInventoryCommand(result.ReservationId)))
//     .Step("ProcessPayment",
//         () => mediator.SendAsync<ProcessPaymentCommand, ProcessPaymentResult>(cmd),
//         result => mediator.SendAsync(new RefundPaymentCommand(result.PaymentId)))
//     .ExecuteAsync();
