using Catga.Core;
using MemoryPack;
using OrderSystem.Api.Domain;
using Catga.Abstractions;

namespace OrderSystem.Api.Messages;

/// <summary>
/// Create order command (with auto-generated debug capture via Source Generator)
/// Demonstrates: CQRS pattern, automatic error handling, rollback mechanism
/// </summary>
[MemoryPackable]
public partial record CreateOrderCommand(
    string CustomerId,
    List<OrderItem> Items,
    string ShippingAddress,
    string PaymentMethod
) : IRequest<OrderCreatedResult>;  // MessageId will be auto-generated by Source Generator


[MemoryPackable]
public partial record OrderCreatedResult(
    string OrderId,
    decimal TotalAmount,
    DateTime CreatedAt
);

/// <summary>
/// Cancel order command
/// Demonstrates: Simple command handling, state transitions
/// </summary>
[MemoryPackable]
public partial record CancelOrderCommand(
    string OrderId,
    string Reason
) : IRequest;  // MessageId will be auto-generated by Source Generator

/// <summary>
/// Get order query
/// Demonstrates: Query pattern, read model
/// </summary>
[MemoryPackable]
public partial record GetOrderQuery(
    string OrderId
) : IRequest<Order?>;  // MessageId will be auto-generated by Source Generator

