using Catga.Core;
using Catga.Flow;
using MemoryPack;
using OrderSystem.Api.Domain;
using Catga.Abstractions;

namespace OrderSystem.Api.Messages;

/// <summary>
/// Create order command (with auto-generated debug capture via Source Generator)
/// Demonstrates: CQRS pattern, automatic error handling, rollback mechanism
/// </summary>
[MemoryPackable]
public partial record CreateOrderCommand(
    string CustomerId,
    List<OrderItem> Items,
    string ShippingAddress,
    string PaymentMethod
) : IRequest<OrderCreatedResult>;  // MessageId will be auto-generated by Source Generator

/// <summary>
/// Create order command using Flow orchestration for automatic compensation.
/// Demonstrates: Zero-cost saga pattern with automatic rollback on failure.
///
/// Flow steps with automatic compensation:
/// 1. Check Inventory (read-only, no compensation)
/// 2. Create Order → Compensation: Mark order as failed
/// 3. Reserve Inventory → Compensation: Release inventory
/// 4. Process Payment → Compensation: Refund payment
/// 5. Confirm Order (final step, no compensation)
///
/// On any failure, compensations execute in reverse order automatically.
/// </summary>
[MemoryPackable]
public partial record CreateOrderFlowCommand(
    string CustomerId,
    List<OrderItem> Items,
    string ShippingAddress,
    string PaymentMethod
) : IRequest<OrderCreatedResult>;

[MemoryPackable]
public partial record OrderCreatedResult(
    string OrderId,
    decimal TotalAmount,
    DateTime CreatedAt
);

/// <summary>
/// Cancel order command
/// Demonstrates: Simple command handling, state transitions
/// </summary>
[MemoryPackable]
public partial record CancelOrderCommand(
    string OrderId,
    string Reason
) : IRequest;  // MessageId will be auto-generated by Source Generator

/// <summary>
/// Get order query
/// Demonstrates: Query pattern, read model
/// </summary>
[MemoryPackable]
public partial record GetOrderQuery(
    string OrderId
) : IRequest<Order?>;  // MessageId will be auto-generated by Source Generator

// ===== Flow 服务编排示例 =====
// 使用 [Compensation] 属性标记命令，失败时自动回滚

/// <summary>
/// Reserve inventory command with automatic compensation
/// </summary>
[MemoryPackable]
[Compensation(typeof(ReleaseInventoryCommand))]
public partial record ReserveInventoryCommand(
    string OrderId,
    List<OrderItem> Items
) : IRequest<ReserveInventoryResult>;

[MemoryPackable]
public partial record ReserveInventoryResult(string ReservationId);

/// <summary>
/// Release inventory command (compensation for ReserveInventory)
/// </summary>
[MemoryPackable]
public partial record ReleaseInventoryCommand(string ReservationId) : IRequest;

/// <summary>
/// Process payment command with automatic compensation
/// </summary>
[MemoryPackable]
[Compensation(typeof(RefundPaymentCommand))]
public partial record ProcessPaymentCommand(
    string OrderId,
    decimal Amount,
    string PaymentMethod
) : IRequest<ProcessPaymentResult>;

[MemoryPackable]
public partial record ProcessPaymentResult(string PaymentId);

/// <summary>
/// Refund payment command (compensation for ProcessPayment)
/// </summary>
[MemoryPackable]
public partial record RefundPaymentCommand(string PaymentId) : IRequest;

// ===== 扩展指南 =====
// 💡 如何使用 Flow 服务编排？
//
// 1. 定义命令并标记补偿：
//    [Compensation(typeof(CancelOrderCommand))]
//    public partial record CreateOrderCommand(...) : IRequest<OrderCreatedResult>;
//
// 2. 在业务代码中使用 Flow：
//    await using var flow = mediator.BeginFlow("CreateOrder");
//    var order = await flow.ExecuteAsync<CreateOrderCommand, OrderCreatedResult>(cmd, ct);
//    var stock = await flow.ExecuteAsync<ReserveInventoryCommand, ReserveInventoryResult>(cmd, ct);
//    var payment = await flow.ExecuteAsync<ProcessPaymentCommand, ProcessPaymentResult>(cmd, ct);
//    flow.Commit(); // 成功，不执行补偿
//    // 任何步骤失败，Dispose 时自动逆序执行补偿
//
// 3. 或者使用 RunFlowAsync：
//    var result = await mediator.RunFlowAsync("CreateOrder", async flow => {
//        var order = await flow.ExecuteAsync<CreateOrderCommand, OrderCreatedResult>(cmd, ct);
//        return order.Value;
//    });
//
// Source Generator 会自动生成 ICompensatable 实现，无需手动编写！
