using Catga.Abstractions;
using FluentAssertions;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace Catga.Tests.E2E;

/// <summary>
/// TDD tests for Catga AspNetCore Endpoint integration
/// Tests the [CatgaEndpoint] attribute and source-generated RegisterEndpoints method
/// </summary>
public class AspNetCoreEndpointE2ETests
{
    [Fact]
    public async Task RegisterEndpoint_ShouldMapPostEndpoint_WhenAttributeMarksMethod()
    {
        // Arrange
        var builder = WebApplication.CreateBuilder();
        builder.Services.AddCatga();
        builder.Services.AddCatgaHandlers();

        var app = builder.Build();

        // Act - Register endpoint
        app.RegisterEndpoint<TestOrderHandlers>();

        // Assert - Verify endpoint is registered
        var endpoints = app.Services.GetRequiredService<IEndpointRouteBuilder>()
            as ICollection<Endpoint>;

        endpoints.Should().NotBeNull();
    }

    [Fact]
    public async Task CatgaEndpoint_ShouldGeneratePartialRegisterEndpointsMethod()
    {
        // Arrange
        var handler = new TestOrderHandlers();

        // Act - Call generated method
        var method = typeof(TestOrderHandlers).GetMethod("RegisterEndpoints",
            System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static);

        // Assert - Method should exist and be generated
        method.Should().NotBeNull("RegisterEndpoints method should be generated by source generator");
        method!.ReturnType.Should().Be(typeof(void));
    }

    [Fact]
    public async Task PartialMethod_ShouldBeImplementedByUser()
    {
        // Arrange
        var handler = new TestOrderHandlers();

        // Act - Call partial method
        var cmd = new TestCreateOrderCommand { CustomerId = "cust-001", Amount = 100 };
        var mediator = new MockCatgaMediator();
        var eventStore = new MockEventStore();

        var result = handler.CreateOrder(cmd, mediator, eventStore);

        // Assert - Partial method should be callable
        result.Should().NotBeNull();
    }

    [Fact]
    public async Task RegisterEndpoint_ShouldSupportChainedCalls()
    {
        // Arrange
        var builder = WebApplication.CreateBuilder();
        builder.Services.AddCatga();
        builder.Services.AddCatgaHandlers();

        var app = builder.Build();

        // Act - Chain multiple endpoint registrations
        var registrar = app.RegisterEndpoint<TestOrderHandlers>();

        // Assert - Should return IEndpointRegistrar for chaining
        registrar.Should().NotBeNull();
        registrar.Should().BeAssignableTo<IEndpointRegistrar>();
    }

    [Fact]
    public async Task ChainedRegisterEndpoint_ShouldRegisterMultipleHandlers()
    {
        // Arrange
        var builder = WebApplication.CreateBuilder();
        builder.Services.AddCatga();
        builder.Services.AddCatgaHandlers();

        var app = builder.Build();

        // Act - Register multiple handlers in chain
        var result = app.RegisterEndpoint<TestOrderHandlers>()
            .RegisterEndpoint<TestOrderHandlers>();

        // Assert - Should support fluent chaining
        result.Should().NotBeNull();
    }
}

/// <summary>
/// Test handler with [CatgaEndpoint] attributes
/// </summary>
public partial class TestOrderHandlers
{
    [CatgaEndpoint(HttpMethod.Post, "/api/orders", Name = "CreateOrder")]
    public partial Task<IResult> CreateOrder(
        TestCreateOrderCommand cmd,
        ICatgaMediator mediator,
        IEventStore eventStore);

    [CatgaEndpoint(HttpMethod.Get, "/api/orders/{id}", Name = "GetOrder")]
    public partial Task<IResult> GetOrder(
        TestGetOrderQuery query,
        ICatgaMediator mediator);
}

/// <summary>
/// User implementation of partial methods
/// </summary>
public partial class TestOrderHandlers
{
    public partial async Task<IResult> CreateOrder(
        TestCreateOrderCommand cmd,
        ICatgaMediator mediator,
        IEventStore eventStore)
    {
        var result = await mediator.SendAsync<TestCreateOrderCommand, TestOrderResult>(cmd);

        if (!result.IsSuccess)
            return Results.BadRequest(new { error = result.Error });

        await eventStore.AppendAsync("orders", new IEvent[]
        {
            new TestOrderCreatedEvent { OrderId = result.Value.OrderId }
        }, 0);

        return Results.Created($"/api/orders/{result.Value.OrderId}", result.Value);
    }

    public partial async Task<IResult> GetOrder(
        TestGetOrderQuery query,
        ICatgaMediator mediator)
    {
        var result = await mediator.SendAsync<TestGetOrderQuery, TestOrderDto>(query);
        return result.IsSuccess ? Results.Ok(result.Value) : Results.NotFound();
    }
}

// Test request/response types
public class TestCreateOrderCommand : IRequest<TestOrderResult>
{
    public string CustomerId { get; set; }
    public decimal Amount { get; set; }
}

public class TestGetOrderQuery : IRequest<TestOrderDto>
{
    public string Id { get; set; }
}

public class TestOrderResult
{
    public string OrderId { get; set; }
    public string CustomerId { get; set; }
    public decimal Amount { get; set; }
}

public class TestOrderDto
{
    public string OrderId { get; set; }
    public string CustomerId { get; set; }
    public decimal Amount { get; set; }
}

public class TestOrderCreatedEvent : IEvent
{
    public string OrderId { get; set; }
}

// Mock implementations for testing
public class MockCatgaMediator : ICatgaMediator
{
    public async Task<CatgaResult<TResponse>> SendAsync<TRequest, TResponse>(TRequest request)
        where TRequest : IRequest<TResponse>
    {
        if (request is TestCreateOrderCommand createCmd)
        {
            var result = new TestOrderResult
            {
                OrderId = Guid.NewGuid().ToString(),
                CustomerId = createCmd.CustomerId,
                Amount = createCmd.Amount
            };
            return CatgaResult<TResponse>.Success((TResponse)(object)result);
        }

        if (request is TestGetOrderQuery getQuery)
        {
            var result = new TestOrderDto
            {
                OrderId = getQuery.Id,
                CustomerId = "cust-001",
                Amount = 100
            };
            return CatgaResult<TResponse>.Success((TResponse)(object)result);
        }

        return CatgaResult<TResponse>.Failure("Unknown request");
    }

    public async Task<CatgaResult> SendAsync<TRequest>(TRequest request) where TRequest : IRequest
    {
        return CatgaResult.Success();
    }

    public async Task<IAsyncEnumerable<TResponse>> StreamAsync<TRequest, TResponse>(TRequest request)
        where TRequest : IStreamRequest<TResponse>
    {
        throw new NotImplementedException();
    }

    public async Task<CatgaResult> PublishAsync<TEvent>(TEvent @event) where TEvent : IEvent
    {
        return CatgaResult.Success();
    }

    public async Task<CatgaResult> PublishAsync<TEvent>(params TEvent[] events) where TEvent : IEvent
    {
        return CatgaResult.Success();
    }
}

public class MockEventStore : IEventStore
{
    private readonly List<IEvent> _events = new();

    public async Task<CatgaResult> AppendAsync<TEvent>(string streamName, TEvent[] events, long expectedVersion)
        where TEvent : IEvent
    {
        _events.AddRange(events);
        return CatgaResult.Success();
    }

    public async Task<CatgaResult<IReadOnlyList<TEvent>>> ReadAsync<TEvent>(string streamName, long fromVersion = 0)
        where TEvent : IEvent
    {
        return CatgaResult<IReadOnlyList<TEvent>>.Success(_events.OfType<TEvent>().ToList().AsReadOnly());
    }

    public async Task<CatgaResult> SubscribeAsync<TEvent>(string streamName, Func<TEvent, Task> handler)
        where TEvent : IEvent
    {
        return CatgaResult.Success();
    }
}
