using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Catga.SourceGenerator;

[Generator]
public sealed class EventTypeRegistryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var eventTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => IsCandidate(node),
                static (ctx, _) => GetEventType(ctx))
            .Where(static t => t is not null)
            .Collect();

        context.RegisterSourceOutput(eventTypes, static (spc, items) =>
        {
            var list = items.Where(i => i is not null)!.Select(i => i!).ToList();
            spc.AddSource("CatgaGenerated.EventTypeRegistry.Init.g.cs", SourceText.From(GenerateModuleInitializer(list), Encoding.UTF8));
        });
    }

    private static bool IsCandidate(SyntaxNode node)
    {
        if (node is not TypeDeclarationSyntax t) return false;
        if (t.BaseList is null || t.BaseList.Types.Count == 0) return false;
        if (t.Parent is TypeDeclarationSyntax) return false; // skip nested for simplicity
        return true;
    }

    private static string? GetEventType(GeneratorSyntaxContext context)
    {
        var t = (TypeDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(t) as INamedTypeSymbol;
        if (symbol is null) return null;
        var implementsEvent = symbol.AllInterfaces.Any(i => i.Name == "IEvent");
        if (!implementsEvent) return null;
        var ns = symbol.ContainingNamespace?.ToDisplayString();
        var fullName = string.IsNullOrEmpty(ns) ? symbol.Name : ns + "." + symbol.Name;
        return fullName;
    }

    private static string GenerateModuleInitializer(IReadOnlyList<string> eventTypeFullNames)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Catga.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class EventTypeRegistryInit");
        sb.AppendLine("    {");
        sb.AppendLine("        [ModuleInitializer]");
        sb.AppendLine("        internal static void Initialize()");
        sb.AppendLine("        {");
        foreach (var fullName in eventTypeFullNames.Distinct().OrderBy(n => n))
        {
            sb.AppendLine($"            Catga.Generated.EventTypeRegistry.Register<{fullName}>();");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
