using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Catga.SourceGenerator;

/// <summary>
/// Source generator for Flow DSL registration without reflection.
/// Auto-discovers all FlowConfig implementations and generates registration code.
/// </summary>
[Generator]
public sealed class FlowDslRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Discover all FlowConfig<T> implementations
        var flowConfigs = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax c && c.BaseList is not null,
                static (ctx, _) => GetFlowConfigInfo(ctx))
            .Where(static f => f is not null)
            .Collect();

        context.RegisterSourceOutput(flowConfigs, static (spc, items) =>
        {
            var flows = items.Where(i => i is not null).ToList();
            // Always generate the class, even if empty
            spc.AddSource("CatgaGeneratedFlowRegistrations.g.cs",
                SourceText.From(GenerateFlowRegistrations(flows!), Encoding.UTF8));
        });
    }

    private static FlowConfigInfo? GetFlowConfigInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (symbol is null || symbol.IsAbstract) return null;

        // Check if it inherits from FlowConfig<T>
        var baseType = symbol.BaseType;
        while (baseType != null)
        {
            if (baseType.IsGenericType &&
                baseType.Name == "FlowConfig" &&
                baseType.ContainingNamespace?.ToDisplayString() == "Catga.Flow.Dsl")
            {
                var stateType = baseType.TypeArguments.FirstOrDefault();
                if (stateType != null)
                {
                    return new FlowConfigInfo(
                        symbol.ToDisplayString(),
                        stateType.ToDisplayString(),
                        symbol.Name,
                        symbol.ContainingNamespace?.ToDisplayString() ?? "Global"
                    );
                }
            }
            baseType = baseType.BaseType;
        }

        return null;
    }

    private static string GenerateFlowRegistrations(IReadOnlyList<FlowConfigInfo> flows)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Catga.Flow.Dsl;");
        sb.AppendLine("using Catga.Flow.Extensions;");
        sb.AppendLine();
        sb.AppendLine("namespace Catga.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Auto-generated Flow DSL registrations");
        sb.AppendLine($"    /// Found {flows.Count} flow configuration(s)");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static partial class CatgaGeneratedFlowRegistrations");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Registers all auto-discovered flow configurations");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddGeneratedFlows(this IServiceCollection services)");
        sb.AppendLine("        {");

        if (flows.Count == 0)
        {
            sb.AppendLine("            // No flow configurations found");
        }
        else
        {
            sb.AppendLine("            // Register flow configurations");
            foreach (var flow in flows.OrderBy(f => f.FlowType))
            {
                // Register as FlowConfig<TState>
                sb.AppendLine($"            services.AddScoped<FlowConfig<{flow.StateType}>, {flow.FlowType}>();");

                // Register as concrete type
                sb.AppendLine($"            services.AddScoped<{flow.FlowType}>();");

                // Register executor
                sb.AppendLine($"            services.AddTransient<DslFlowExecutor<{flow.StateType}, {flow.FlowType}>>();");
                sb.AppendLine();
            }
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Generate individual registration methods for each flow
        foreach (var flow in flows.OrderBy(f => f.FlowType))
        {
            var methodName = $"Add{flow.FlowName}";
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Register {flow.FlowName} flow");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public static IServiceCollection {methodName}(this IServiceCollection services)");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            services.AddScoped<FlowConfig<{flow.StateType}>, {flow.FlowType}>();");
            sb.AppendLine($"            services.AddScoped<{flow.FlowType}>();");
            sb.AppendLine($"            services.AddTransient<DslFlowExecutor<{flow.StateType}, {flow.FlowType}>>();");
            sb.AppendLine($"            return services;");
            sb.AppendLine($"        }}");
            sb.AppendLine();
        }

        // Generate factory methods
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Get all registered flow types");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static System.Collections.Generic.IReadOnlyList<FlowRegistration> GetRegisteredFlows()");
        sb.AppendLine("        {");
        sb.AppendLine("            return new FlowRegistration[]");
        sb.AppendLine("            {");

        foreach (var flow in flows.OrderBy(f => f.FlowType))
        {
            sb.AppendLine($"                new FlowRegistration(\"{flow.FlowName}\", typeof({flow.StateType}), typeof({flow.FlowType})),");
        }

        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate FlowRegistration record
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Flow registration metadata");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public record FlowRegistration(string Name, System.Type StateType, System.Type FlowType);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private sealed class FlowConfigInfo
    {
        public string FlowType { get; }
        public string StateType { get; }
        public string FlowName { get; }
        public string Namespace { get; }

        public FlowConfigInfo(string flowType, string stateType, string flowName, string @namespace)
        {
            FlowType = flowType;
            StateType = stateType;
            FlowName = flowName;
            Namespace = @namespace;
        }
    }
}
