using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Catga.SourceGenerator;

[Generator]
public sealed class MediatorBatchProfilesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => GetInfo(ctx)
        ).Where(static x => x is not null).Collect();

        context.RegisterSourceOutput(candidates, static (spc, items) =>
        {
            var list = items!.OfType<ReqInfo>().ToList();
            spc.AddSource("CatgaGenerated.MediatorBatchProfiles.Init.g.cs", SourceText.From(GenerateBootstrap(list), Encoding.UTF8));
        });
    }

    private static ReqInfo? GetInfo(GeneratorSyntaxContext context)
    {
        var typeDecl = (TypeDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(typeDecl) is not INamedTypeSymbol symbol) return null;
        if (symbol.IsAbstract) return null;

        bool IsRequestInterface(INamedTypeSymbol i)
        {
            var name = i.Name;
            var ns = i.ContainingNamespace?.ToDisplayString();
            return ns == "Catga.Abstractions" && name == "IRequest" && (i.TypeArguments.Length == 0 || i.TypeArguments.Length == 1);
        }

        bool implementsIRequest = symbol.AllInterfaces.Any(IsRequestInterface);
        if (!implementsIRequest) return null;

        // Read attributes on the request type
        var attrs = symbol.GetAttributes();
        var optionsAttr = attrs.FirstOrDefault(a => a.AttributeClass?.Name == "BatchOptionsAttribute");
        var keyAttr = attrs.FirstOrDefault(a => a.AttributeClass?.Name == "BatchKeyAttribute");

        if (optionsAttr is null && keyAttr is null)
        {
            // No need to generate anything for this request type
            return null;
        }

        var info = new ReqInfo(symbol.ToDisplayString());

        if (optionsAttr is not null)
        {
            int GetInt(string name)
            {
                var arg = optionsAttr.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value;
                return arg.Value is int v ? v : 0;
            }

            info.MaxBatchSize = GetInt("MaxBatchSize");
            info.BatchTimeoutMs = GetInt("BatchTimeoutMs");
            info.MaxQueueLength = GetInt("MaxQueueLength");
            info.ShardIdleTtlMs = GetInt("ShardIdleTtlMs");
            info.MaxShards = GetInt("MaxShards");
            info.FlushDegree = GetInt("FlushDegree");
        }

        if (keyAttr is not null)
        {
            // Positional ctor: BatchKeyAttribute(string propertyName)
            if (keyAttr.ConstructorArguments.Length == 1 && keyAttr.ConstructorArguments[0].Value is string s)
            {
                info.KeyPropertyName = s;
                // Try to get property type
                var prop = symbol.GetMembers().OfType<IPropertySymbol>().FirstOrDefault(p => p.Name == s);
                if (prop is not null)
                {
                    info.KeyIsString = prop.Type.SpecialType == SpecialType.System_String;
                    info.KeyIsValueType = prop.Type.IsValueType && prop.Type.SpecialType != SpecialType.System_String;
                }
            }
        }

        return info;
    }

    private static string GenerateBootstrap(IReadOnlyList<ReqInfo> infos)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Catga.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class MediatorBatchProfilesBootstrap");
        sb.AppendLine("    {");
        sb.AppendLine("        [ModuleInitializer]");
        sb.AppendLine("        internal static void Initialize()");
        sb.AppendLine("        {");
        sb.AppendLine("            global::Catga.Generated.GeneratedBootstrapRegistry.Register(static services =>");
        sb.AppendLine("            {");
        if (infos.Count == 0)
        {
            sb.AppendLine("                // No mediator batch profiles discovered");
        }
        else
        {
            foreach (var i in infos)
            {
                if (i.HasAnyOptions)
                {
                    sb.Append("                global::Catga.Pipeline.MediatorBatchProfiles.RegisterOptionsTransformer<");
                    sb.Append(i.RequestType);
                    sb.Append(">(static global => global with { ");
                    bool first = true;
                    void AppendComma()
                    {
                        if (!first) sb.Append(", ");
                        first = false;
                    }
                    if (i.MaxBatchSize > 0) { AppendComma(); sb.Append("MaxBatchSize = ").Append(i.MaxBatchSize); }
                    if (i.BatchTimeoutMs > 0) { AppendComma(); sb.Append("BatchTimeout = global::System.TimeSpan.FromMilliseconds(").Append(i.BatchTimeoutMs).Append(")"); }
                    if (i.MaxQueueLength > 0) { AppendComma(); sb.Append("MaxQueueLength = ").Append(i.MaxQueueLength); }
                    if (i.ShardIdleTtlMs > 0) { AppendComma(); sb.Append("ShardIdleTtl = global::System.TimeSpan.FromMilliseconds(").Append(i.ShardIdleTtlMs).Append(")"); }
                    if (i.MaxShards > 0) { AppendComma(); sb.Append("MaxShards = ").Append(i.MaxShards); }
                    if (i.FlushDegree > 0) { AppendComma(); sb.Append("FlushDegree = ").Append(i.FlushDegree); }
                    sb.Append(" });");
                    sb.AppendLine();
                }

                if (!string.IsNullOrWhiteSpace(i.KeyPropertyName))
                {
                    sb.Append("                global::Catga.Pipeline.MediatorBatchProfiles.RegisterKeySelector<");
                    sb.Append(i.RequestType);
                    sb.Append(">(static r => ");
                    if (i.KeyIsString)
                    {
                        sb.Append("r.").Append(i.KeyPropertyName);
                    }
                    else if (i.KeyIsValueType)
                    {
                        sb.Append("r.").Append(i.KeyPropertyName).Append(".ToString()");
                    }
                    else
                    {
                        sb.Append("r.").Append(i.KeyPropertyName).Append("?.ToString()");
                    }
                    sb.AppendLine(");");
                }
            }
        }
        sb.AppendLine("            });");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private sealed class ReqInfo
    {
        public string RequestType { get; }
        public int MaxBatchSize { get; set; }
        public int BatchTimeoutMs { get; set; }
        public int MaxQueueLength { get; set; }
        public int ShardIdleTtlMs { get; set; }
        public int MaxShards { get; set; }
        public int FlushDegree { get; set; }
        public string? KeyPropertyName { get; set; }
        public bool KeyIsString { get; set; }
        public bool KeyIsValueType { get; set; }

        public bool HasAnyOptions => MaxBatchSize > 0 || BatchTimeoutMs > 0 || MaxQueueLength > 0 || ShardIdleTtlMs > 0 || MaxShards > 0 || FlushDegree > 0;

        public ReqInfo(string requestType)
        {
            RequestType = requestType;
        }
    }
}
