using Catga;
using Catga.Abstractions;
using Catga.Core;
using Catga.Flow;
using Microsoft.Extensions.Logging;
using OrderSystem.Api.Domain;
using OrderSystem.Api.Messages;
using OrderSystem.Api.Services;

namespace OrderSystem.Api.Handlers;

/// <summary>
/// Order creation handler using Flow orchestration.
///
/// Auto-generated by framework:
/// - HandleAsync wrapper with telemetry (from [CatgaHandler])
/// - ExecuteFlowAsync from [FlowStep] methods
/// - Activity/Span with request properties as tags
/// - Duration, count, error metrics
/// </summary>
[CatgaHandler]
[Metric("order.flow.amount", Type = MetricType.Histogram, Unit = "USD")]
public sealed partial class CreateOrderFlowHandler : IRequestHandler<CreateOrderFlowCommand, OrderCreatedResult>
{
    private readonly IOrderRepository _orderRepository;
    private readonly IInventoryService _inventoryService;
    private readonly IPaymentService _paymentService;
    private readonly ICatgaMediator _mediator;
    private readonly ILogger<CreateOrderFlowHandler> _logger;

    public CreateOrderFlowHandler(
        IOrderRepository orderRepository,
        IInventoryService inventoryService,
        IPaymentService paymentService,
        ICatgaMediator mediator,
        ILogger<CreateOrderFlowHandler> logger)
    {
        _orderRepository = orderRepository;
        _inventoryService = inventoryService;
        _paymentService = paymentService;
        _mediator = mediator;
        _logger = logger;
    }

    // Flow context - shared between steps
    private Order _order = null!;
    private decimal _totalAmount;

    /// <summary>
    /// Pure business logic - telemetry wrapper is auto-generated.
    /// </summary>
    private async Task<CatgaResult<OrderCreatedResult>> HandleAsyncCore(
        CreateOrderFlowCommand request,
        CancellationToken ct)
    {
        _totalAmount = request.Items.Sum(i => i.Subtotal);
        _order = new Order
        {
            OrderId = $"FLOW-{DateTime.UtcNow:yyyyMMddHHmmss}-{Guid.NewGuid():N}"[..36],
            CustomerId = request.CustomerId,
            Items = request.Items,
            TotalAmount = _totalAmount,
            Status = OrderStatus.Pending,
            CreatedAt = DateTime.UtcNow,
            ShippingAddress = request.ShippingAddress,
            PaymentMethod = request.PaymentMethod
        };

        // ExecuteFlowAsync is auto-generated from [FlowStep] methods below
        var flowResult = await ExecuteFlowAsync(ct);

        return flowResult.IsSuccess
            ? CatgaResult<OrderCreatedResult>.Success(new OrderCreatedResult(_order.OrderId, _totalAmount, _order.CreatedAt))
            : CatgaResult<OrderCreatedResult>.Failure(flowResult.Error ?? "Flow failed");
    }

    // Flow steps - order defined by [FlowStep(Order = N)]
    // Compensation methods are called in reverse order on failure

    [FlowStep(Order = 1)]
    private Task CheckInventory(CancellationToken ct)
        => _inventoryService.CheckStockAsync(_order.Items, ct).AsTask();

    [FlowStep(Order = 2, Compensate = nameof(MarkOrderFailed))]
    private Task SaveOrder(CancellationToken ct)
        => _orderRepository.SaveAsync(_order, ct).AsTask();

    private async Task MarkOrderFailed(CancellationToken ct)
    {
        _order.Status = OrderStatus.Failed;
        await _orderRepository.UpdateAsync(_order, ct);
    }

    [FlowStep(Order = 3, Compensate = nameof(ReleaseInventory))]
    private Task ReserveInventory(CancellationToken ct)
        => _inventoryService.ReserveStockAsync(_order.OrderId, _order.Items, ct).AsTask();

    private Task ReleaseInventory(CancellationToken ct)
        => _inventoryService.ReleaseStockAsync(_order.OrderId, _order.Items, ct).AsTask();

    [FlowStep(Order = 4, Compensate = nameof(RefundPayment))]
    private Task ProcessPayment(CancellationToken ct)
        => _paymentService.ProcessPaymentAsync(_order.OrderId, _totalAmount, _order.PaymentMethod, ct).AsTask();

    private Task RefundPayment(CancellationToken ct)
    {
        _logger.LogWarning("Refunding order {OrderId}", _order.OrderId);
        return Task.CompletedTask;
    }

    [FlowStep(Order = 5)]
    private async Task ConfirmOrder(CancellationToken ct)
    {
        _order.Status = OrderStatus.Confirmed;
        await _orderRepository.UpdateAsync(_order, ct);
        await _mediator.PublishAsync(new OrderCreatedEvent(
            _order.OrderId, _order.CustomerId, _order.Items, _order.TotalAmount, _order.CreatedAt), ct);
    }
}
